@url = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmb29iYXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjI5NTM1NTAsImV4cCI6MTc2Mjk1NzE1MH0.E8ttirNCvKzfuzAt5vL-bQDbHawXz10Mc1j1-HD2X10


### Fetch recipe data from external API (HTML response to parse)
GET https://encuisine.adrienrossignol.fr/recette/41
Accept: text/html

# L'indicqteur de budget, temps de prepartion et difficulte figure dans la page html sous forme d'icones a compterr
# temps_rouge.svg = 2 icones = 2
# difficulte_rouge.svg = 2 icones = 2
# budget_rouges.svg = 2 icone = 2


### Athenticate and obtain JWT token or signup new user
### This step is optional if you already have a valid token

### Create new user
POST {{url}}/api/auth/local/register
Content-Type: application/json

{
  "username": "foobar",
  "email": "foobar@example.com",
  "password": "foobarpassword"
}

### Authenticate existing user

POST {{url}}/api/auth/local
Content-Type: application/json

{
  "identifier": "foobar@example.com",
  "password": "foobarpassword"
}

### Create new recette in Express API
POST {{url}}/api/recipes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titre": "Poêlée de patate douce et feta",
  "temps_de_preparation": 2,
  "difficulte": 1,
  "budget": 1,
  "description": "Pelez les patates douces et coupez-les en petits cubes.Faites-les revenir dans une poêle 10 minutes avec un filet d'huile d'olive..."
}

###

### Get all recipes to verify creation
GET {{url}}/api/recipes
Accept: application/json
Authorization: Bearer {{token}}

###

### Get specific recette by ID (replace {id} with actual ID)
GET {{url}}/api/recipes/1
Accept: application/json
Authorization: Bearer {{token}}


### Update specific recette by ID (replace {id} with actual ID)
PUT {{url}}/api/recipes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "description": "Mise a jour de la description de la recette."
  }
}


### Delete specific recette by ID (replace {id} with actual ID)
DELETE {{url}}/api/recipes/1
Accept: application/json
Authorization: Bearer {{token}}
